apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-victorvanhoecke
  namespace: exam-nginx
  labels:
    app: nginx
    exam: containers-orchestration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        exam: containers-orchestration
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
