version: '3.9'

services:
  web:
    build: ./pointsApp
    ports:
      - 5000:8080
    environment:
      FLASK_SECRET_KEY: a2V5
      SECRET_KEY: SG9wZWxpamsgZ2VicnVpa3QgZWVuIHN0dWRlbnQgZGl0IG9vaXQgbnV0dGlnLg==
    volumes:
      - ./web/webapp/static:/app/webapp/static
    networks:
      - web
      - database

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    environment:
      - POSTGRES_DB=labo
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - database

networks:
  web:
  database:

volumes:
  postgres:
