version: '3.9'

services:
  web:
    build: ./pointsApp
    ports:
      - 5000:8080
    volumes:
      - ./web/webapp/static:/app/webapp/static
    networks:
      - web
      - database
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_user -d labo"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - database

networks:
  web:
  database:

volumes:
  postgres:
